version: "3"
services:
  web:
    container_name: config-management-web
    image: config-management-web:0.3
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      # Overwrite the placeholder config.json with the actual one at runtime
      - ./config.json:/usr/src/app/src/config.json:ro
