---
- name: Backup and Copy Network Device Configurations
  hosts: network_devices
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Get Current Date and Time
      command: date -u +"%Y-%m-%dT%H:%M:%SZ"
      register: current_datetime
    - name: Config Backup
      ios_config:
        backup: yes
        backup_options:
          dir_path: "/backups/{{ inventory_hostname }}"
      register: config_output
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - name: Move backup file to sanitized filename
      command: mv {{ config_output.backup_path }} /backups/{{ inventory_hostname }}/{{ inventory_hostname }}_config_{{ current_datetime.stdout }}.txt
      args:
        removes: "{{ config_output.backup_path }}"

    - name: Output Backup Details
      debug:
        msg:
          hostname: "{{ inventory_hostname }}"
          filename: "{{ inventory_hostname }}_config_{{ current_datetime.stdout }}.txt"
          datetime: "{{ current_datetime.stdout }}"
          filepath: "/backups/{{ inventory_hostname }}/{{ inventory_hostname }}_config_{{ current_datetime.stdout }}.txt"
