---
- name: Backup Configurations for Linux Hosts
  hosts: linux_hosts
  gather_facts: no
  connection: ssh
  become: yes
  tasks:
    - name: Get Current Date and Time
      command: date -u +"%Y-%m-%dT%H-%M-%SZ"
      register: current_datetime

    - name: Ensure backup directory exists on the Ansible control node
      file:
        path: "/backups/{{ inventory_hostname }}"
        state: directory
        mode: '0755'

    - name: Copy /etc/hosts file to a temporary location on the remote host
      command: cp /etc/hosts /tmp/{{ inventory_hostname }}_hosts_{{ current_datetime.stdout }}.hosts

    - name: Fetch the backup of /etc/hosts from the remote hosts
      fetch:
        src: "/tmp/{{ inventory_hostname }}_hosts_{{ current_datetime.stdout }}.hosts"
        dest: "/backups/{{ inventory_hostname }}/"
        flat: yes

    - name: Cleanup the temporary hosts backup on the remote host
      file:
        path: "/tmp/{{ inventory_hostname }}_hosts_{{ current_datetime.stdout }}.hosts"
        state: absent
    
    - name: Output Backup Details
      debug:
        msg:
          hostname: "{{ inventory_hostname }}"
          filename: "{{ inventory_hostname }}_config_{{ current_datetime.stdout }}.txt"
          datetime: "{{ current_datetime.stdout }}"
          filepath: "/backups/{{ inventory_hostname }}/{{ inventory_hostname }}_config_{{ current_datetime.stdout }}.txt"
