version: '2.2'

services:
  web:
    container_name: ciscocollector
    restart: always
    image: ciscocollector:0.1
    network_mode: "host"
    ports:
      - "9000:9000"
    volumes:
      - /home/config-mgmt-collector/src:/ciscocollector:rw
      - /home/config-mgmt-collector/config:/ciscocollector/config:rw
      - /home/config-mgmt-collector/backups:/backups:rw
