openapi: 3.0.0
info:
  title: Config management swagger for backend APIs
  description: This is swagger for documenation of all backend APIs being used for config management tool.
  version: 1.0.0
servers:
  - url: http://9.46.66.96:9000
paths:
  /health:
    get:
      summary: Health Check
      description: Returns the health status of the service.
      responses:
        '200':
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "Healthy"
        '500':
          description: Service is unhealthy
          content:
            text/plain:
              schema:
                type: string
                example: "Unhealthy"
  /backup:
    post:
      summary: Get the backup of devices
      requestBody:
        description: It collects backup of devices and store on predifined directory.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inventory:
                  type: array
                  items:
                    type: object
                    properties:
                      hostname:
                        type: string
                      ipaddress:
                        type: string
                      username:
                        type: string
                      password:
                        type: string
      responses:
        201:
          description: Successfully collected the inventory
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Backup collected successfully"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
  /config_files/list:
    get:
      summary: List config files for a specific hostname
      parameters:
        - in: query
          name: hostname
          schema:
            type: string
          description: The hostname to filter config files
          required: true
      responses:
        '200':
          description: A list of config files for the specified hostname
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    filename:
                      type: string
        '400':
          description: Invalid input
        '404':
          description: Hostname not found
  /config_files/view:
    get:
      summary: View a specific config file
      parameters:
        - in: query
          name: hostname
          schema:
            type: string
          description: The hostname to filter config files
          required: true
        - in: query
          name: filename
          schema:
            type: string
          description: The filename to view
          required: true
      responses:
        '200':
          description: The contents of the specified config file
          content:
            application/json:
              schema:
                type: object
                properties:
                  hostname:
                    type: string
                  filename:
                    type: string
                  content:
                    type: string
                    description: The contents of the config file
        '400':
          description: Invalid input
        '404':
          description: Config file not found
  /config_files/download:
    get:
      summary: Download a specific config file
      parameters:
        - in: query
          name: hostname
          schema:
            type: string
          description: The hostname associated with the config file
          required: true
        - in: query
          name: filename
          schema:
            type: string
          description: The name of the config file to download
          required: false
      responses:
        '200':
          description: The config file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid input
        '404':
          description: Config file not found
  /config_files/downloadall:
    get:
      summary: Download all backup files
      parameters:
        - in: query
          name: hostname
          schema:
            type: string
          description: The hostname associated with the config file
          required: true
      responses:
        '200':
          description: The config files
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid input
        '404':
          description: hostname not found